// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"fmt"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	"github.com/podossaem/podoroot/application/api"
	"github.com/podossaem/podoroot/application/config"
	"github.com/podossaem/podoroot/domain/user"
	"github.com/podossaem/podoroot/domain/user/app"
	persist2 "github.com/podossaem/podoroot/domain/user/persist"
	"github.com/podossaem/podoroot/domain/verification"
	app2 "github.com/podossaem/podoroot/domain/verification/app"
	"github.com/podossaem/podoroot/domain/verification/persist"
	"github.com/podossaem/podoroot/infra/database"
	"github.com/podossaem/podoroot/infra/database/mymongo"
)

// Injectors from app.go:

func Start() error {
	client := mymongo.NewClient()
	emailVerificationRepository := persist.NewEmailVerificationRepository(client)
	emailVerificationService := verification.NewEmailVerificationService(emailVerificationRepository)
	userRepository := persist2.NewUserRepository(client)
	userService := user.NewUserService(emailVerificationService, userRepository)
	userController := app.NewUserController(userService)
	userRouter := app.NewUserRouter(userController)
	emailVerificationController := app2.NewEmailVerificationController(emailVerificationService)
	verificationRouter := app2.NewVerificationRouter(emailVerificationController)
	router := api.NewRouter(userRouter, verificationRouter)
	error2 := StartApplication(router, client)
	return error2
}

// app.go:

func StartApplication(
	router api.Router,
	mymongoClient *mymongo.Client,
) error {
	if err := database.Init(mymongoClient); err != nil {
		return err
	}
	app3 := echo.New()
	app3.
		Use(middleware.Logger())
	router.Attach(app3)

	if err := app3.Start(fmt.Sprintf(":%d", config.AppPort())); err != nil {
		return err
	}

	defer func() {
		if err := database.Dispose(mymongoClient); err != nil {
			panic(err)
		}
	}()

	return nil
}
