// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"fmt"
	"github.com/labstack/echo/v4"
	"github.com/podossaem/podoroot/application/config"
	"github.com/podossaem/podoroot/application/middleware"
	"github.com/podossaem/podoroot/application/router"
	"github.com/podossaem/podoroot/domain/auth"
	"github.com/podossaem/podoroot/domain/auth/app"
	"github.com/podossaem/podoroot/domain/me"
	app2 "github.com/podossaem/podoroot/domain/me/app"
	"github.com/podossaem/podoroot/domain/user"
	app3 "github.com/podossaem/podoroot/domain/user/app"
	persist2 "github.com/podossaem/podoroot/domain/user/persist"
	"github.com/podossaem/podoroot/domain/verification"
	app4 "github.com/podossaem/podoroot/domain/verification/app"
	"github.com/podossaem/podoroot/domain/verification/persist"
	"github.com/podossaem/podoroot/infra/database"
	"github.com/podossaem/podoroot/infra/database/mymongo"
	"github.com/podossaem/podoroot/infra/database/myredis"
)

// Injectors from app.go:

func Start() error {
	client := mymongo.NewClient()
	myredisClient := myredis.NewClient()
	emailVerificationRepository := persist.NewEmailVerificationRepository(client)
	emailVerificationService := verification.NewEmailVerificationService(emailVerificationRepository)
	userRepository := persist2.NewUserRepository(client)
	userService := user.NewUserService(userRepository)
	authService := auth.NewAuthService(emailVerificationService, userService)
	authController := app.NewAuthController(authService)
	authRouter := app.NewAuthRouter(authController)
	meService := me.NewMeService(userRepository)
	meController := app2.NewMeController(meService)
	meRouter := app2.NewMeRouter(meController)
	userController := app3.NewUserController()
	userRouter := app3.NewUserRouter(userController)
	emailVerificationController := app4.NewEmailVerificationController(emailVerificationService)
	verificationRouter := app4.NewVerificationRouter(emailVerificationController)
	routerRouter := router.New(authRouter, meRouter, userRouter, verificationRouter)
	error2 := StartApplication(client, myredisClient, routerRouter)
	return error2
}

// app.go:

func StartApplication(
	mymongoClient *mymongo.Client,
	myredisClient *myredis.Client, router2 router.Router,

) error {
	if err := database.Init(
		mymongoClient,
		myredisClient,
	); err != nil {
		return err
	}
	app5 := echo.New()
	app5.
		Use(middleware.New()...)
	router2.
		Attach(app5)

	if err := app5.Start(fmt.Sprintf(":%d", config.AppPort())); err != nil {
		return err
	}

	defer func() {
		if err := database.Dispose(mymongoClient); err != nil {
			panic(err)
		}
	}()

	return nil
}
